CREATE TABLE public.tb001_parametro (
	idparametro serial,
	idademinima int NULL,
	qtdcursosimultaneo int NULL,
	PRIMARY KEY (idparametro)
);

CREATE TABLE public.tb002_estudante (
	idestudante serial,
	datanascimento date NULL,
	email varchar(255) NULL,
	nome varchar(255) NULL,
	senha varchar(255) NULL,
	sobrenome varchar(255) NULL,
	telefone varchar(255) NULL,
	PRIMARY KEY (idestudante)
);

CREATE TABLE public.tb003_curso (
	idcurso int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	descricaocurso varchar(255) NULL,
	nomecurso varchar(255) NULL,
	PRIMARY KEY (idcurso)
);

CREATE TABLE public.tb004_matriculas (
	id serial PRIMARY KEY,
	data_matricula date NULL,
	idcurso int8 NULL,
	idestudante int8 NULL,
	status varchar(255) NULL,
	FOREIGN KEY (idcurso) REFERENCES tb003_curso(idcurso),
	FOREIGN KEY (idestudante) REFERENCES tb002_estudante(idestudante)
);

CREATE TABLE public.tb005_usuario (
	idusuario serial NOT NULL,
	nome varchar NULL,
	login varchar NULL,
	senha varchar NULL,
	PRIMARY KEY (idusuario)
);

CREATE TABLE public.tb006_categoriatarefa (
	idcategoria serial4 NOT NULL,
	descricao varchar NULL,
	PRIMARY KEY (idcategoria)
);

CREATE TABLE public.tb007_tarefa (
	idtarefa serial NOT NULL,
	"data" date NULL,
	idcategoria int8 NULL,
	descricao varchar NULL,
	tempo int NULL,
	FOREIGN KEY (idcategoria) REFERENCES public.tb006_categoriatarefa(idcategoria)
);

CREATE OR REPLACE VIEW view001_USUARIOS AS 
SELECT te.idestudante AS idLogin, te.nome, te.email AS usuario, te.senha, 'ALUNO' AS permissao FROM tb002_estudante te
UNION ALL
SELECT tu.idusuario, tu.nome, tu.login, tu.senha, 'ADM' FROM tb005_usuario tu;

INSERT INTO public.tb005_usuario
(idusuario, nome, login, senha)
VALUES (1, 'ADMIN', 'ADMIN', '$2a$10$I8vfExWOKS4zMBXUt.WlNOKQd4Tg8RAKM.2MhKuDO9pJfY2hCHidq');

INSERT INTO public.tb006_categoriatarefa
(idcategoria, descricao) VALUES (1, 'PESQUISA');
INSERT INTO public.tb006_categoriatarefa
(idcategoria, descricao) VALUES (2, 'PRATICA');
INSERT INTO public.tb006_categoriatarefa
(idcategoria, descricao) VALUES (3, 'ASSISTIR_VIDEOAULA');

INSERT INTO public.tb001_parametro
(idparametro, idademinima, qtdcursosimultaneo)
VALUES(1, 16, 3);
